name: db-tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # weekly Monday 06:00 UTC
jobs:
  db-integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Create test database
        env:
          PGPASSWORD: test
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do sleep 2; done
          psql -h localhost -U postgres -c 'CREATE DATABASE db8_test;'
      - name: Prepare schema/RPC/RLS
        env:
          DATABASE_URL: postgresql://postgres:test@localhost:5432/db8_test
          DB8_TEST_OUTPUT: quiet
        run: node scripts/prepare-db.js
      - name: Run DB-gated tests
        env:
          DB8_TEST_PG: '1'
          DB8_TEST_DATABASE_URL: postgresql://postgres:test@localhost:5432/db8_test
        run: npx vitest run server/test/rpc.db.postgres.test.js server/test/journal.byidx.test.js server/test/watcher.db.flip.test.js --reporter verbose
